name: homesplus
version: 0.0.2
main: org.jeft.homes.Homesplus
api-version: '1.16'
commands:
  sethome:
    description: Set a player home or waypoint
    usage: /<command>
    permission: homesplus.sethome
  homesplus:
    description: Main plugin command
    usage: /<command>
    permission: homesplus.main